### PR TITLE
added functions to get paths to user home, config, app-data directories and temp dir

### PR DESCRIPTION
**Pull request by donbcd**
Hi,
I just added a first draft for getting the paths to
- user home
- config directory
- app-data directory
- temp directory

What do you think about that? Is this useful? 

This is a quick hack and works on Linux and Windows Vista+7. Support for 1) MacOS 2) Older and newer Windows Versions and 3) other posix-systems like android and blackberry is _not_ yet implemented, but not too hard to do. I just can not test them..

### CODE REVIEW

**Comment by retf** [comment]
It seems to be useful. Well, in this version I do not provide support for android, thus no problem! Did you test on MAC OS X too?

**Comment by donbcd** [comment]
I'll implement the Mac support this week, but I don't have a system at home to test it on.

**Comment by retf** [comment]
me too, I don't have any mac to test :(

**Comment by apolukhin** [comment]
[This is how](https://github.com/apolukhin/Boost.DLL/blob/master/include/boost/dll/detail/posix/program_location_impl.hpp) program location is determinated in Boost.DLL. 

Only Windows and Linux parts were tested, but at least this gives some basic idea were to look for paths on other platforms.

**Comment by retf** [comment]
Thanks, I will take a look!

**Pull request merged**
