### PR TITLE
Improve windows path aspect implementation

### PR DESCRIPTION
**Pull request by BurningEnlightenment**
Hello everyone,
The path returned by app_data_path() should point to %USERPROFILE%\AppData\Local\, since user specific application data should not be roamed accross multiple machines.
Furthermore I simplified the implementation quite a bit, which should make it somewhat faster and easier to maintain. For the latter reason I removed the legacy WinXP code and in addition to that it isn't quite a best-practice to target platforms which aren't supported anymore.

### CODE REVIEW

**Comment by retf** [comment]
Hi, thanks for your contribution!

**Comment by Heather** [comment]
@BurningEnlightenment @retf  may you help me with this change

I'm getting following errors now:
``` shell
e\hdr\application\include\boost/application/detail/windows/path_impl.hpp(90): error C2039: 'SHGetKnownFolderPath' : is not a member of '`global namespace''
e\hdr\application\include\boost/application/detail/windows/path_impl.hpp(90): error C2065: 'KF_FLAG_CREATE' : undeclared identifier
e\hdr\application\include\boost/application/detail/windows/path_impl.hpp(90): error C3861: 'SHGetKnownFolderPath': identifier not found
```

win 8.1 / msvc 12

**Comment by retf** [comment]
This is strange, all these symbols are declared in "Shlobj.h" that is included in the path "path_impl.hpp"!  @BurningEnlightenment do you can help here! tks!

**Comment by BurningEnlightenment** [comment]
as I stated I dropped winXP support, so you need to define your NTDDI_VERSION as NTDDI_VISTA or higher.

**Comment by Heather** [comment]
@BurningEnlightenment I'm using win 8.1 so detector works wrong somewhere... maybe it will be better to keep XP support for this case?

**Comment by BurningEnlightenment** [comment]
Your problem is that you didn't define the version of the windows SDK you want to use and the default still seems to be winXP. What we can do is to introduce some preprocesor magic which ensures a minimum windows sdk version and produces a helpful message.

**Comment by Heather** [comment]
@BurningEnlightenment that will force many people to include that prefix header to each codebase but maybe it's right.

**Comment by BurningEnlightenment** [comment]
so I created [WinSdkVerVista.h](https://gist.github.com/BurningEnlightenment/05eef0ba2b569d5e2828) which does the version selection and should be included before every win sdk header at least once if you didn't roll your own win sdk version selection solution.
Furthermore I added an `#error` to path_impl.h which describes the thing and points to the file above. @retf is this sufficient? And if it is I encourage you to pull those additions ;)

**Comment by retf** [comment]
Hi, I dont know if many users of Applicatio uses XP, anyway, send a pull! I will add it!

**Pull request merged**
