### PR TITLE
Revert "fixed crash with std::thread"

### PR DESCRIPTION
**Pull request by retf**
Reverts retf/Boost.Application#42

For some reason this crash on travis, need check it

### CODE REVIEW

**Comment by snikulov** [comment]
Well, it crash on building boost
...failed gcc.compile.c++ ../../../bin.v2/libs/application/test/simple_server_application.test/gcc-4.6/debug/threading-multi/simple_server_application.o...

...failed updating 23 targets...

...skipped 46 targets...

...updated 193 targets...

The command "../../../b2 cxxflags="--coverage -std=$CXX_STANDARD" linkflags="--coverage"" exited with 1.

**Comment by snikulov** [comment]
../../../boost/system/config.hpp:34:3: error: #error Must not define both BOOST_SYSTEM_DYN_LINK and BOOST_SYSTEM_STATIC_LINK

**Comment by snikulov** [comment]
Same result. I suspect, this failure related to boost changes on master.

**Comment by retf** [comment]
Yes, well, I don't have time now. Later I'll investigate! If you have time, send me a new pull! Thanks a lot!

**Comment by snikulov** [comment]
Maybe @apolukhin can help with this build issues? 
It seems to me .travis.yml should be updated, but unfortunately I'm not familiar with bjam stuff.

**Comment by snikulov** [comment]
@retf  Could you please put my https://github.com/retf/Boost.Application/pull/42 back?
As you see - it is not the reason for Travis-CI failure.

**Comment by retf** [comment]
Hi @snikulov ,
You are collaborator now, you can now merg it.

**Pull request merged**
