### PR TITLE
Fix some complie error and complie warnning.

### PR DESCRIPTION
**Pull request by hbccdf**
Use the Boost.Application with vc++ 2015, will have some complie error and complie warning. This commit will fix it.

### CODE REVIEW

**Comment by retf** [comment]
tks

**Comment by Kojoley** [comment]
This is strange because I don't have compile problems with Visual Studio 2015

**Comment by snikulov** [comment]
@Kojoley just guess - maximum warn level. Just brcause I also don't have any issues :)

**Comment by Kojoley** [comment]
@snikulov may be, but only if @hbccdf uses /WX flag too

**Comment by hbccdf** [comment]
@Kojoley , I use **/W3** **/WX-**  with **x64** platform. 
I'm sure will have warning in this way. But i'm not sure the real reason of the compile error.

**Pull request merged**
